// buildroot-web/src/components/Terminal/Terminal.tsx
import { useEffect, useRef, useState, useCallback } from 'react';
import { Terminal as XTerm } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import { WebLinksAddon } from '@xterm/addon-web-links';
import { SearchAddon } from '@xterm/addon-search';
import { Search, X, RotateCcw } from 'lucide-react';
import '@xterm/xterm/css/xterm.css';
import { useWebSocket, usePTYData } from '@/hooks/useWebSocket';
import { MessageType } from '@/types';

interface TerminalProps {
  deviceId: string | null;
}

export function Terminal({ deviceId }: TerminalProps) {
  const terminalRef = useRef<HTMLDivElement>(null);
  const termRef = useRef<XTerm | null>(null);
  const fitAddonRef = useRef<FitAddon | null>(null);
  const searchAddonRef = useRef<SearchAddon | null>(null);
  const sessionIdRef = useRef(0);
  const [connected, setConnected] = useState(false);
  const [showSearch, setShowSearch] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [searchMatches, setSearchMatches] = useState(0);
  const ptyInitializedRef = useRef(false);

  const { send } = useWebSocket();

  const initTerminal = useCallback(() => {
    if (!terminalRef.current || termRef.current) return;

    console.log('[Terminal] Initializing xterm.js...');
    
    const term = new XTerm({
      fontFamily: '"JetBrains Mono", "Fira Code", Consolas, monospace',
      fontSize: 14,
      cursorBlink: true,
      cursorStyle: 'block',
      theme: {
        background: '#1e1e2e',
        foreground: '#cdd6f4',
        cursor: '#f5e0dc',
        black: '#45475a',
        red: '#f38ba8',
        green: '#a6e3a1',
        yellow: '#f9e2af',
        blue: '#89b4fa',
        magenta: '#f5c2e7',
        cyan: '#94e2d5',
        white: '#bac2de',
        brightBlack: '#585b70',
        brightRed: '#eba0ac',
        brightGreen: '#a6e3a1',
        brightYellow: '#f9e2af',
        brightBlue: '#89b4fa',
        brightMagenta: '#f5c2e7',
        brightCyan: '#94e2d5',
        brightWhite: '#a6adc8',
      },
    });

    const fitAddon = new FitAddon();
    const webLinksAddon = new WebLinksAddon();
    const searchAddon = new SearchAddon();

    term.loadAddon(fitAddon);
    term.loadAddon(webLinksAddon);
    term.loadAddon(searchAddon);

    term.open(terminalRef.current);

    setTimeout(() => {
      try {
        fitAddon.fit();
      } catch (e) {
        console.warn('[Terminal] Failed to fit terminal:', e);
      }
    }, 100);

    termRef.current = term;
    fitAddonRef.current = fitAddon;
    searchAddonRef.current = searchAddon;

    console.log('[Terminal] xterm.js initialized');
  }, []);

  const sendPTYData = useCallback((data: string) => {
    if (!deviceId || !termRef.current || !ptyInitializedRef.current) return;
    
    try {
      const encoded = btoa(unescape(encodeURIComponent(data)));
      send(MessageType.PTY_DATA, {
        deviceId,
        sessionId: sessionIdRef.current,
        data: encoded,
      });
    } catch (e) {
      console.error('[Terminal] Error encoding PTY data:', e);
    }
  }, [deviceId, send]);

  const createPTYSession = useCallback(() => {
    if (!deviceId || !termRef.current || !fitAddonRef.current) {
      console.warn('[Terminal] Cannot create PTY: missing deviceId or terminal');
      return;
    }

    sessionIdRef.current = Date.now();
    ptyInitializedRef.current = true;
    
    console.log('[Terminal] Creating PTY session:', {
      deviceId,
      sessionId: sessionIdRef.current,
      rows: termRef.current.rows,
      cols: termRef.current.cols,
    });

    send(MessageType.PTY_CREATE, {
      deviceId,
      sessionId: sessionIdRef.current,
      rows: termRef.current.rows,
      cols: termRef.current.cols,
    });
  }, []);

  useEffect(() => {
    initTerminal();
  }, [initTerminal]);

  useEffect(() => {
    const handleResize = () => {
      if (fitAddonRef.current) {
        fitAddonRef.current.fit();
      }
    };

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  useEffect(() => {
    if (!termRef.current) return;

    const onData = (data: string) => {
      sendPTYData(data);
    };

    const onResize = (size: { rows: number; cols: number }) => {
      if (!deviceId || !ptyInitializedRef.current) return;
      
      console.log('[Terminal] Resizing:', size);
      send(MessageType.PTY_RESIZE, {
        deviceId,
        sessionId: sessionIdRef.current,
        rows: size.rows,
        cols: size.cols,
      });
    };

    termRef.current.onData(onData);
    termRef.current.onResize(onResize);

    return () => {
    };
  }, [deviceId, send]);

  usePTYData(deviceId, (data) => {
    if (termRef.current) {
      termRef.current.write(data);
    }
  });

  useEffect(() => {
    if (!deviceId) {
      ptyInitializedRef.current = false;
      setConnected(false);
      return;
    }

    const timer = setTimeout(() => {
      setConnected(true);
      createPTYSession();
    }, 200);

    return () => {
      clearTimeout(timer);
      if (ptyInitializedRef.current) {
        send(MessageType.PTY_CLOSE, {
          deviceId,
          sessionId: sessionIdRef.current,
        });
      }
    };
  }, [deviceId]);

  const handleSearch = useCallback(() => {
    if (!searchAddonRef.current) return;
    const result = searchAddonRef.current.findNext(searchTerm);
    setSearchMatches(typeof result === 'number' ? result : 0);
  }, []);

  const reconnectTerminal = useCallback(() => {
    ptyInitializedRef.current = false;
    setConnected(false);
    termRef.current?.clear();
    createPTYSession();
  }, []);

  const clearTerminal = useCallback(() => {
    termRef.current?.clear();
  }, []);

  return (
    <div className="h-full flex flex-col bg-bg-primary rounded-lg border border-border overflow-hidden">
      <div className="flex items-center justify-between px-4 py-2 bg-bg-secondary border-b border-border flex-shrink-0">
        <div className="flex items-center gap-3 font-mono text-sm">
          <span className="text-text-muted">bash</span>
          <span className="text-text-muted">•</span>
          <span className="text-accent-primary cursor-pointer">~</span>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => setShowSearch(!showSearch)}
            className="px-2.5 py-1.5 bg-bg-tertiary border border-border rounded text-text-secondary text-xs hover:bg-bg-elevated transition-colors"
            title="搜索 (Ctrl+Shift+F)"
          >
            <Search size={14} />
          </button>
          <button
            onClick={clearTerminal}
            className="px-2.5 py-1.5 bg-bg-tertiary border border-border rounded text-text-secondary text-xs hover:bg-bg-elevated transition-colors"
          >
            清空
          </button>
          <button
            onClick={reconnectTerminal}
            className="px-2.5 py-1.5 bg-bg-tertiary border border-border rounded text-text-secondary text-xs hover:bg-bg-elevated transition-colors"
            title="重新连接"
          >
            <RotateCcw size={14} />
          </button>
        </div>
      </div>

      {showSearch && (
        <div className="flex items-center gap-2 px-4 py-1.5 bg-bg-elevated border-b border-border flex-shrink-0">
          <input
            type="text"
            placeholder="搜索终端内容..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
            className="flex-1 max-w-[300px] px-2.5 py-1 bg-bg-primary border border-border rounded text-text-primary text-xs font-mono outline-none focus:border-accent-primary"
          />
          <span className="text-xs text-text-muted min-w-[60px]">{searchMatches} 个结果</span>
          <button
            onClick={() => {
              if (searchAddonRef.current) {
                searchAddonRef.current.findPrevious(searchTerm);
              }
            }}
            className="px-2 py-1 bg-bg-tertiary border border-border rounded text-text-secondary text-xs"
          >
            ▲
          </button>
          <button
            onClick={handleSearch}
            className="px-2 py-1 bg-bg-tertiary border border-border rounded text-text-secondary text-xs"
          >
            ▼
          </button>
          <button
            onClick={() => setShowSearch(false)}
            className="px-2 py-1 bg-bg-tertiary border border-border rounded text-text-secondary text-xs"
          >
            <X size={12} />
          </button>
        </div>
      )}

      <div className="flex-1 relative overflow-hidden bg-[#1e1e2e]">
        <div ref={terminalRef} className="h-full" />
      </div>

      <div className="flex items-center justify-between px-4 py-1 bg-bg-secondary border-t border-border text-[11px] text-text-muted font-mono flex-shrink-0">
        <div className="flex items-center gap-3">
          <span className="flex items-center gap-1">
            <span className={`w-1.5 h-1.5 rounded-full ${connected ? 'bg-accent-success shadow-[0_0_6px_var(--accent-success)]' : 'bg-text-muted'}`} />
            {connected ? '已连接' : '未连接'}
          </span>
        </div>
        <div>
          {termRef.current && `${termRef.current.cols}×${termRef.current.rows}`}
        </div>
      </div>
    </div>
  );
}

// buildroot-web-vue/src/views/Terminal/index.vue
<template>
  <div class="terminal-container">
    <!-- 工具栏 -->
    <div class="terminal-toolbar">
      <div class="toolbar-left">
        <select v-model="selectedDeviceId" class="device-select" @change="onDeviceChange">
          <option value="">选择设备</option>
          <option 
            v-for="device in devices" 
            :key="device.id" 
            :value="device.id"
          >
            {{ device.name || device.id.slice(0, 8) }} 
            {{ device.is_online ? '(在线)' : '(离线)' }}
          </option>
        </select>
        <button class="toolbar-btn new-tab" @click="openInNewTab" :disabled="!selectedDeviceId">
          新标签页
        </button>
      </div>
      
      <div class="toolbar-center">
        <div class="status-indicator" :class="connectionStatus">
          <span class="status-dot"></span>
          <span class="status-text">{{ statusText }}</span>
        </div>
      </div>
      
      <div class="toolbar-right">
        <button 
          class="toolbar-btn connect" 
          @click="connect"
          :disabled="!canConnect"
        >
          连接
        </button>
        <button 
          class="toolbar-btn disconnect" 
          @click="disconnect"
          :disabled="!connected"
        >
          断开
        </button>
        <button 
          class="toolbar-btn" 
          @click="clearTerminal"
          :disabled="!terminal"
        >
          清屏
        </button>
      </div>
    </div>
    
    <!-- 终端区域 -->
    <div class="terminal-wrapper" ref="terminalWrapper">
      <div ref="terminalElement" class="terminal"></div>
    </div>
    
    <!-- 错误提示 -->
    <div v-if="error" class="terminal-error">
      {{ error }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Terminal } from '@xterm/xterm'
import { FitAddon } from '@xterm/addon-fit'
import { useDeviceStore } from '@/stores/device'
import { useTabStore } from '@/stores/tabs'
import { getWebSocketClient, MessageType } from '@/api/websocket'

const route = useRoute()
const router = useRouter()
const deviceStore = useDeviceStore()
const tabStore = useTabStore()

// Refs
const terminalWrapper = ref<HTMLElement>()
const terminalElement = ref<HTMLElement>()
const terminal = ref<Terminal | null>(null)
const selectedDeviceId = ref('')
const sessionId = ref<number | null>(null)
const connectionStatus = ref<'disconnected' | 'connecting' | 'connected'>('disconnected')
const error = ref('')
const connecting = ref(false)

// Computed
const devices = computed(() => deviceStore.devices)
const connected = computed(() => connectionStatus.value === 'connected')
const canConnect = computed(() => {
  const device = devices.value.find(d => d.id === selectedDeviceId.value)
  return selectedDeviceId.value && device?.is_online && !connected.value && !connecting.value
})
const statusText = computed(() => {
  switch (connectionStatus.value) {
    case 'connected': return '已连接'
    case 'connecting': return '连接中...'
    default: return '未连接'
  }
})

// WebSocket client
let wsClient: ReturnType<typeof getWebSocketClient> | null = null
let messageHandler: ((msg: any) => void) | null = null

// Methods
const initTerminal = () => {
  if (terminal.value || !terminalElement.value) return
  
  const term = new Terminal({
    cursorBlink: true,
    cursorStyle: 'block',
    fontSize: 14,
    fontFamily: 'JetBrains Mono, Monaco, Menlo, monospace',
    theme: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      cursor: '#f5e0dc',
      selectionBackground: 'rgba(245, 224, 220, 0.3)',
      black: '#45475a',
      red: '#f38ba8',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      blue: '#89b4fa',
      magenta: '#f5c2e7',
      cyan: '#94e2d5',
      white: '#bac2de',
      brightBlack: '#585b70',
      brightRed: '#f38ba8',
      brightGreen: '#a6e3a1',
      brightYellow: '#f9e2af',
      brightBlue: '#89b4fa',
      brightMagenta: '#f5c2e7',
      brightCyan: '#94e2d5',
      brightWhite: '#a6adc8',
    }
  })
  
  const addon = new FitAddon()
  term.loadAddon(addon)
  term.open(terminalElement.value)
  
  setTimeout(() => addon.fit(), 100)
  
  terminal.value = term
  
  term.onData((data) => {
    if (sessionId.value && wsClient) {
      wsClient.send(MessageType.PTY_DATA, {
        session_id: sessionId.value,
        data: data
      })
    }
  })
  
  term.onResize(({ cols, rows }) => {
    if (sessionId.value && wsClient) {
      wsClient.send(MessageType.PTY_RESIZE, {
        session_id: sessionId.value,
        cols,
        rows
      })
    }
  })
  
  term.writeln('\x1b[36mBuildroot Agent 终端\x1b[0m')
  term.writeln('')
}

const connect = async () => {
  if (!selectedDeviceId.value) return
  
  const device = devices.value.find(d => d.id === selectedDeviceId.value)
  if (!device?.is_online) {
    error.value = '设备离线'
    return
  }
  
  connecting.value = true
  connectionStatus.value = 'connecting'
  error.value = ''
  
  initTerminal()
  
  terminal.value?.writeln(`\x1b[33m连接 ${device.name || selectedDeviceId.value}...\x1b[0m`)
  
  if (!wsClient) {
    wsClient = getWebSocketClient()
    
    messageHandler = (msg: any) => {
      handleWebSocketMessage(msg)
    }
    wsClient.on('message', messageHandler)
    
    wsClient.on('disconnected', () => {
      connectionStatus.value = 'disconnected'
      sessionId.value = null
    })
    
    wsClient.connect()
  }
  
  setTimeout(() => {
    if (wsClient && terminal.value) {
      const { cols, rows } = terminal.value
      wsClient.send(MessageType.PTY_CREATE, {
        device_id: selectedDeviceId.value,
        cols: cols || 80,
        rows: rows || 24
      })
    }
  }, 500)
}

const disconnect = () => {
  if (sessionId.value && wsClient) {
    wsClient.send(MessageType.PTY_CLOSE, {
      session_id: sessionId.value
    })
  }
  
  connectionStatus.value = 'disconnected'
  sessionId.value = null
  terminal.value?.writeln('\x1b[33m已断开\x1b[0m')
}

const clearTerminal = () => {
  terminal.value?.clear()
}

const onDeviceChange = () => {
  if (selectedDeviceId.value) {
    router.replace(`/terminal/${selectedDeviceId.value}`)
    
    const device = devices.value.find(d => d.id === selectedDeviceId.value)
    if (device) {
      tabStore.openTab('terminal', selectedDeviceId.value, device.name || selectedDeviceId.value.slice(0, 8))
    }
  } else {
    router.replace('/terminal')
  }
  
  if (connected.value) {
    disconnect()
  }
  sessionId.value = null
  error.value = ''
}

const openInNewTab = () => {
  if (selectedDeviceId.value) {
    const url = `${window.location.origin}/terminal/${selectedDeviceId.value}`
    window.open(url, '_blank')
  }
}

const handleWebSocketMessage = (msg: any) => {
  const { type, data } = msg
  
  if (type === MessageType.PTY_CREATE) {
    if (data.session_id) {
      sessionId.value = data.session_id
      connecting.value = false
      connectionStatus.value = 'connected'
      terminal.value?.writeln('\x1b[32m连接成功\x1b[0m')
    } else {
      connecting.value = false
      connectionStatus.value = 'disconnected'
      terminal.value?.writeln(`\x1b[31m连接失败: ${data.error || '未知错误'}\x1b[0m`)
      error.value = data.error || '连接失败'
    }
  }
  
  if (type === MessageType.PTY_DATA && data.session_id === sessionId.value) {
    terminal.value?.write(data.data)
  }
  
  if (type === MessageType.PTY_CLOSE && data.session_id === sessionId.value) {
    connectionStatus.value = 'disconnected'
    sessionId.value = null
    terminal.value?.writeln('\x1b[33m会话已关闭\x1b[0m')
  }
}

// Lifecycle
onMounted(async () => {
  await deviceStore.fetchDevices()
  
  initTerminal()
  
  const deviceId = route.params.deviceId as string
  if (deviceId) {
    selectedDeviceId.value = deviceId
    const device = devices.value.find(d => d.id === deviceId)
    if (device) {
      tabStore.openTab('terminal', deviceId, device.name || deviceId.slice(0, 8))
    }
  }
})

onBeforeUnmount(() => {
  if (connected.value) {
    disconnect()
  }
  
  if (wsClient && messageHandler) {
    wsClient.off('message', messageHandler)
  }
  
  terminal.value?.dispose()
})

watch(() => route.params.deviceId, (newDeviceId) => {
  if (newDeviceId && typeof newDeviceId === 'string') {
    selectedDeviceId.value = newDeviceId
    if (connected.value) {
      disconnect()
    }
    const device = devices.value.find(d => d.id === newDeviceId)
    if (device) {
      tabStore.openTab('terminal', newDeviceId, device.name || newDeviceId.slice(0, 8))
    }
  }
})
</script>

<style scoped>
.terminal-container {
  display: flex;
  flex-direction: column;
  height: 100%;
  background: #1e1e2e;
}

.terminal-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 8px 16px;
  background: #181825;
  border-bottom: 1px solid #313244;
}

.toolbar-left,
.toolbar-right {
  display: flex;
  gap: 8px;
}

.toolbar-center {
  display: flex;
  align-items: center;
}

.device-select {
  padding: 6px 12px;
  background: #1e1e2e;
  border: 1px solid #45475a;
  border-radius: 4px;
  color: #cdd6f4;
  font-size: 13px;
}

.device-select:focus {
  outline: none;
  border-color: #89b4fa;
}

.toolbar-btn {
  padding: 6px 12px;
  background: #313244;
  border: 1px solid #45475a;
  border-radius: 4px;
  color: #cdd6f4;
  font-size: 13px;
  cursor: pointer;
  transition: all 0.2s;
}

.toolbar-btn:hover:not(:disabled) {
  background: #45475a;
}

.toolbar-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.toolbar-btn.connect {
  background: #a6e3a1;
  color: #1e1e2e;
  border-color: #a6e3a1;
}

.toolbar-btn.disconnect {
  background: #f38ba8;
  color: #1e1e2e;
  border-color: #f38ba8;
}

.toolbar-btn.new-tab {
  background: #89b4fa;
  color: #1e1e2e;
}

.status-indicator {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 4px 12px;
  background: #1e1e2e;
  border-radius: 12px;
  font-size: 12px;
}

.status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #f38ba8;
}

.status-indicator.connected .status-dot {
  background: #a6e3a1;
}

.status-indicator.connecting .status-dot {
  background: #f9e2af;
  animation: pulse 1s infinite;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

.status-text {
  color: #6c7086;
}

.terminal-wrapper {
  flex: 1;
  padding: 8px;
  overflow: hidden;
}

.terminal {
  height: 100%;
}

.terminal-error {
  position: fixed;
  bottom: 20px;
  right: 20px;
  padding: 12px 20px;
  background: #f38ba8;
  color: #1e1e2e;
  border-radius: 4px;
  font-size: 13px;
}
</style>
