// buildroot-web/src/components/Terminal/Terminal.tsx
import { useEffect, useRef, useState, useCallback } from 'react';
import { Terminal as XTerm } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import { WebLinksAddon } from '@xterm/addon-web-links';
import { SearchAddon } from '@xterm/addon-search';
import { Search, X, RotateCcw } from 'lucide-react';
import '@xterm/xterm/css/xterm.css';
import { useWebSocket, usePTYData } from '@/hooks/useWebSocket';
import { MessageType } from '@/types';

interface TerminalProps {
  deviceId: string | null;
}

export function Terminal({ deviceId }: TerminalProps) {
  const terminalRef = useRef<HTMLDivElement>(null);
  const termRef = useRef<XTerm | null>(null);
  const fitAddonRef = useRef<FitAddon | null>(null);
  const searchAddonRef = useRef<SearchAddon | null>(null);
  const sessionIdRef = useRef(0);
  const [connected, setConnected] = useState(false);
  const [showSearch, setShowSearch] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [searchMatches, setSearchMatches] = useState(0);
  const ptyInitializedRef = useRef(false);

  const { send } = useWebSocket();

  const initTerminal = useCallback(() => {
    if (!terminalRef.current || termRef.current) return;

    console.log('[Terminal] Initializing xterm.js...');
    
    const term = new XTerm({
      fontFamily: '"JetBrains Mono", "Fira Code", Consolas, monospace',
      fontSize: 14,
      cursorBlink: true,
      cursorStyle: 'block',
      theme: {
        background: '#1e1e2e',
        foreground: '#cdd6f4',
        cursor: '#f5e0dc',
        black: '#45475a',
        red: '#f38ba8',
        green: '#a6e3a1',
        yellow: '#f9e2af',
        blue: '#89b4fa',
        magenta: '#f5c2e7',
        cyan: '#94e2d5',
        white: '#bac2de',
        brightBlack: '#585b70',
        brightRed: '#eba0ac',
        brightGreen: '#a6e3a1',
        brightYellow: '#f9e2af',
        brightBlue: '#89b4fa',
        brightMagenta: '#f5c2e7',
        brightCyan: '#94e2d5',
        brightWhite: '#a6adc8',
      },
    });

    const fitAddon = new FitAddon();
    const webLinksAddon = new WebLinksAddon();
    const searchAddon = new SearchAddon();

    term.loadAddon(fitAddon);
    term.loadAddon(webLinksAddon);
    term.loadAddon(searchAddon);

    term.open(terminalRef.current);

    setTimeout(() => {
      try {
        fitAddon.fit();
      } catch (e) {
        console.warn('[Terminal] Failed to fit terminal:', e);
      }
    }, 100);

    termRef.current = term;
    fitAddonRef.current = fitAddon;
    searchAddonRef.current = searchAddon;

    console.log('[Terminal] xterm.js initialized');
  }, []);

  const sendPTYData = useCallback((data: string) => {
    if (!deviceId || !termRef.current || !ptyInitializedRef.current) return;
    
    try {
      const encoded = btoa(unescape(encodeURIComponent(data)));
      send(MessageType.PTY_DATA, {
        deviceId,
        sessionId: sessionIdRef.current,
        data: encoded,
      });
    } catch (e) {
      console.error('[Terminal] Error encoding PTY data:', e);
    }
  }, [deviceId, send]);

  const createPTYSession = useCallback(() => {
    if (!deviceId || !termRef.current || !fitAddonRef.current) {
      console.warn('[Terminal] Cannot create PTY: missing deviceId or terminal');
      return;
    }

    sessionIdRef.current = Date.now();
    ptyInitializedRef.current = true;
    
    console.log('[Terminal] Creating PTY session:', {
      deviceId,
      sessionId: sessionIdRef.current,
      rows: termRef.current.rows,
      cols: termRef.current.cols,
    });

    send(MessageType.PTY_CREATE, {
      deviceId,
      sessionId: sessionIdRef.current,
      rows: termRef.current.rows,
      cols: termRef.current.cols,
    });
  }, []);

  useEffect(() => {
    initTerminal();
  }, [initTerminal]);

  useEffect(() => {
    const handleResize = () => {
      if (fitAddonRef.current) {
        fitAddonRef.current.fit();
      }
    };

    window.addEventListener('resize', handleResize);
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  useEffect(() => {
    if (!termRef.current) return;

    const onData = (data: string) => {
      sendPTYData(data);
    };

    const onResize = (size: { rows: number; cols: number }) => {
      if (!deviceId || !ptyInitializedRef.current) return;
      
      console.log('[Terminal] Resizing:', size);
      send(MessageType.PTY_RESIZE, {
        deviceId,
        sessionId: sessionIdRef.current,
        rows: size.rows,
        cols: size.cols,
      });
    };

    termRef.current.onData(onData);
    termRef.current.onResize(onResize);

    return () => {
    };
  }, [deviceId, send]);

  usePTYData(deviceId, (data) => {
    if (termRef.current) {
      termRef.current.write(data);
    }
  });

  useEffect(() => {
    if (!deviceId) {
      ptyInitializedRef.current = false;
      setConnected(false);
      return;
    }

    const timer = setTimeout(() => {
      setConnected(true);
      createPTYSession();
    }, 200);

    return () => {
      clearTimeout(timer);
      if (ptyInitializedRef.current) {
        send(MessageType.PTY_CLOSE, {
          deviceId,
          sessionId: sessionIdRef.current,
        });
      }
    };
  }, [deviceId]);

  const handleSearch = useCallback(() => {
    if (!searchAddonRef.current) return;
    const result = searchAddonRef.current.findNext(searchTerm);
    setSearchMatches(typeof result === 'number' ? result : 0);
  }, []);

  const reconnectTerminal = useCallback(() => {
    ptyInitializedRef.current = false;
    setConnected(false);
    termRef.current?.clear();
    createPTYSession();
  }, []);

  const clearTerminal = useCallback(() => {
    termRef.current?.clear();
  }, []);

  return (
    <div className="h-full flex flex-col bg-bg-primary rounded-lg border border-border overflow-hidden">
      <div className="flex items-center justify-between px-4 py-2 bg-bg-secondary border-b border-border flex-shrink-0">
        <div className="flex items-center gap-3 font-mono text-sm">
          <span className="text-text-muted">bash</span>
          <span className="text-text-muted">•</span>
          <span className="text-accent-primary cursor-pointer">~</span>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => setShowSearch(!showSearch)}
            className="px-2.5 py-1.5 bg-bg-tertiary border border-border rounded text-text-secondary text-xs hover:bg-bg-elevated transition-colors"
            title="搜索 (Ctrl+Shift+F)"
          >
            <Search size={14} />
          </button>
          <button
            onClick={clearTerminal}
            className="px-2.5 py-1.5 bg-bg-tertiary border border-border rounded text-text-secondary text-xs hover:bg-bg-elevated transition-colors"
          >
            清空
          </button>
          <button
            onClick={reconnectTerminal}
            className="px-2.5 py-1.5 bg-bg-tertiary border border-border rounded text-text-secondary text-xs hover:bg-bg-elevated transition-colors"
            title="重新连接"
          >
            <RotateCcw size={14} />
          </button>
        </div>
      </div>

      {showSearch && (
        <div className="flex items-center gap-2 px-4 py-1.5 bg-bg-elevated border-b border-border flex-shrink-0">
          <input
            type="text"
            placeholder="搜索终端内容..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
            className="flex-1 max-w-[300px] px-2.5 py-1 bg-bg-primary border border-border rounded text-text-primary text-xs font-mono outline-none focus:border-accent-primary"
          />
          <span className="text-xs text-text-muted min-w-[60px]">{searchMatches} 个结果</span>
          <button
            onClick={() => {
              if (searchAddonRef.current) {
                searchAddonRef.current.findPrevious(searchTerm);
              }
            }}
            className="px-2 py-1 bg-bg-tertiary border border-border rounded text-text-secondary text-xs"
          >
            ▲
          </button>
          <button
            onClick={handleSearch}
            className="px-2 py-1 bg-bg-tertiary border border-border rounded text-text-secondary text-xs"
          >
            ▼
          </button>
          <button
            onClick={() => setShowSearch(false)}
            className="px-2 py-1 bg-bg-tertiary border border-border rounded text-text-secondary text-xs"
          >
            <X size={12} />
          </button>
        </div>
      )}

      <div className="flex-1 relative overflow-hidden bg-[#1e1e2e]">
        <div ref={terminalRef} className="h-full" />
      </div>

      <div className="flex items-center justify-between px-4 py-1 bg-bg-secondary border-t border-border text-[11px] text-text-muted font-mono flex-shrink-0">
        <div className="flex items-center gap-3">
          <span className="flex items-center gap-1">
            <span className={`w-1.5 h-1.5 rounded-full ${connected ? 'bg-accent-success shadow-[0_0_6px_var(--accent-success)]' : 'bg-text-muted'}`} />
            {connected ? '已连接' : '未连接'}
          </span>
        </div>
        <div>
          {termRef.current && `${termRef.current.cols}×${termRef.current.rows}`}
        </div>
      </div>
    </div>
  );
}

// buildroot-web-v2/src/views/Terminal/index.vue
<script setup lang="ts">
/**
 * 终端组件 - xterm.js + WebSocket
 * 用于远程设备 PTY 会话
 */
import { ref, computed, onMounted, onBeforeUnmount, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Terminal } from '@xterm/xterm'
import { FitAddon } from '@xterm/addon-fit'
import { WebLinksAddon } from '@xterm/addon-web-links'
import Button from 'primevue/button'
import Select from 'primevue/select'
import Tag from 'primevue/tag'
import { getWebSocketClient, MessageType } from '@/api/websocket'

interface Device {
  device_id: string
  name?: string
  is_online: boolean
}

const route = useRoute()
const router = useRouter()

// Refs
const terminalWrapper = ref<HTMLElement>()
const terminalElement = ref<HTMLElement>()
const terminal = ref<Terminal | null>(null)
const fitAddon = ref<FitAddon | null>(null)
const selectedDeviceId = ref<string>('')
const sessionId = ref<number | null>(null)
const connectionStatus = ref<'disconnected' | 'connecting' | 'connected'>('disconnected')
const error = ref('')
const devices = ref<Device[]>([])
const wsConnected = ref(false)

// Computed
const onlineDevices = computed(() =>
  devices.value.filter(d => d.is_online)
)
const connected = computed(() => connectionStatus.value === 'connected')
const canConnect = computed(() => {
  const device = devices.value.find(d => d.device_id === selectedDeviceId.value)
  const result = selectedDeviceId.value && device?.is_online && !connected.value
  console.log('[Terminal] canConnect:', result, 'selectedDeviceId:', selectedDeviceId.value, 'device:', device)
  return result
})
const statusText = computed(() => {
  switch (connectionStatus.value) {
    case 'connected': return '已连接'
    case 'connecting': return '连接中...'
    default: return '未连接'
  }
})
const statusSeverity = computed(() => {
  switch (connectionStatus.value) {
    case 'connected': return 'success'
    case 'connecting': return 'warn'
    default: return 'secondary'
  }
})

// WebSocket
let wsClient: ReturnType<typeof getWebSocketClient> | null = null
let messageHandler: ((msg: unknown) => void) | null = null

// 初始化 WebSocket
const initWebSocket = () => {
  console.log('[Terminal] initWebSocket called')
  const client = getWebSocketClient()
  wsClient = client
  console.log('[Terminal] ws status:', client.getStatus(), 'isConnected:', client.isConnected())

  messageHandler = (msg: unknown) => {
    handleWebSocketMessage(msg)
  }
  client.on('message', messageHandler)

  client.on('connected', () => {
    console.log('[Terminal] WS connected event')
    wsConnected.value = true
    // 请求设备列表
    client.send(MessageType.DEVICE_LIST, { page: 0, page_size: 100 })
  })

  client.on('disconnected', () => {
    wsConnected.value = false
    connectionStatus.value = 'disconnected'
    sessionId.value = null
  })

  // 如果已连接，直接请求设备列表
  if (client.isConnected()) {
    console.log('[Terminal] Already connected, sending DEVICE_LIST')
    wsConnected.value = true
    client.send(MessageType.DEVICE_LIST, { page: 0, page_size: 100 })
  } else {
    console.log('[Terminal] Not connected, calling connect()')
    client.connect()
  }
}

// 初始化终端
const initTerminal = () => {
  if (terminal.value || !terminalElement.value) return

  const term = new Terminal({
    cursorBlink: true,
    cursorStyle: 'block',
    fontSize: 14,
    fontFamily: 'JetBrains Mono, Monaco, Menlo, "Courier New", monospace',
    lineHeight: 1.2,
    theme: {
      background: '#1e1e2e',
      foreground: '#cdd6f4',
      cursor: '#f5e0dc',
      selectionBackground: 'rgba(245, 224, 220, 0.3)',
      black: '#45475a',
      red: '#f38ba8',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      blue: '#89b4fa',
      magenta: '#f5c2e7',
      cyan: '#94e2d5',
      white: '#bac2de',
      brightBlack: '#585b70',
      brightRed: '#f38ba8',
      brightGreen: '#a6e3a1',
      brightYellow: '#f9e2af',
      brightBlue: '#89b4fa',
      brightMagenta: '#f5c2e7',
      brightCyan: '#94e2d5',
      brightWhite: '#a6adc8',
    },
  })

  const addon = new FitAddon()
  term.loadAddon(addon)
  term.loadAddon(new WebLinksAddon())
  term.open(terminalElement.value)

  fitAddon.value = addon
  terminal.value = term

  // 延迟 fit，等待 DOM 渲染
  setTimeout(() => addon.fit(), 100)

  // 用户输入 -> 发送到设备
  term.onData((data) => {
    if (sessionId.value && wsClient) {
      wsClient.send(MessageType.PTY_DATA, {
        session_id: sessionId.value,
        data,
      })
    }
  })

  // 终端大小变化 -> 通知设备
  term.onResize(({ cols, rows }) => {
    if (sessionId.value && wsClient) {
      wsClient.send(MessageType.PTY_RESIZE, {
        session_id: sessionId.value,
        cols,
        rows,
      })
    }
  })

  term.writeln('')
  term.writeln('  Buildroot Agent Terminal')
  term.writeln('  ========================')
  term.writeln('')
  term.writeln('  Select device and click Connect')
  term.writeln('')
}

// 连接设备
const connect = async () => {
  if (!selectedDeviceId.value) return

  const device = devices.value.find(d => d.device_id === selectedDeviceId.value)
  if (!device?.is_online) {
    error.value = '设备离线'
    return
  }

  connectionStatus.value = 'connecting'
  error.value = ''

  initTerminal()

  terminal.value?.writeln(`\x1b[33m连接 ${device.name || selectedDeviceId.value.slice(0, 8)}...\x1b[0m`)

  // 确保 WebSocket 已连接
  if (!wsClient) {
    initWebSocket()
    // 等待连接
    await new Promise(resolve => setTimeout(resolve, 500))
  }

  // 发送 PTY_CREATE 请求
  if (wsClient && terminal.value) {
    const { cols, rows } = terminal.value
    // 生成 session_id (简单递增)
    const newSessionId = Date.now()
    wsClient.send(MessageType.PTY_CREATE, {
      device_id: selectedDeviceId.value,
      session_id: newSessionId,
      cols: cols || 80,
      rows: rows || 24,
    })
    console.log('[Terminal] PTY_CREATE sent, session_id:', newSessionId)
  }
}

// 断开连接
const disconnect = () => {
  if (sessionId.value && wsClient) {
    wsClient.send(MessageType.PTY_CLOSE, {
      session_id: sessionId.value,
    })
  }

  connectionStatus.value = 'disconnected'
  sessionId.value = null
  terminal.value?.writeln('\x1b[33m已断开\x1b[0m')
}

// 清屏
const clearTerminal = () => {
  terminal.value?.clear()
}

// 处理 WebSocket 消息
const handleWebSocketMessage = (msg: unknown) => {
  const message = msg as { type: number; data: Record<string, unknown> }
  const { type, data } = message
  
  console.log('[Terminal] 收到消息:', type, data)

  // DEVICE_LIST 响应
  if (type === MessageType.DEVICE_LIST) {
    const deviceList = data.devices as Device[] || []
    devices.value = deviceList.map(d => ({
      ...d,
      name: d.name || d.device_id.slice(0, 12), // 默认显示 device_id 前12位
      is_online: true, // WebSocket 返回的都是在线设备
    }))
    console.log('[Terminal] 设备列表更新:', devices.value.length, devices.value)
  }

  // PTY_CREATE 响应
  if (type === MessageType.PTY_CREATE) {
    if (data.session_id) {
      sessionId.value = data.session_id as number
      connectionStatus.value = 'connected'
      terminal.value?.writeln('\x1b[32m连接成功\x1b[0m')
    } else {
      connectionStatus.value = 'disconnected'
      terminal.value?.writeln(`\x1b[31m连接失败: ${data.error || '未知错误'}\x1b[0m`)
      error.value = (data.error as string) || '连接失败'
    }
  }

  // PTY_DATA 输出
  if (type === MessageType.PTY_DATA && data.session_id === sessionId.value) {
    terminal.value?.write(data.data as string)
  }

  // PTY_CLOSE 会话关闭
  if (type === MessageType.PTY_CLOSE && data.session_id === sessionId.value) {
    connectionStatus.value = 'disconnected'
    sessionId.value = null
    terminal.value?.writeln('\x1b[33m会话已关闭\x1b[0m')
  }
}

// 设备选择变化
const onDeviceChange = () => {
  console.log('[Terminal] onDeviceChange, selectedDeviceId:', selectedDeviceId.value)
  if (selectedDeviceId.value) {
    router.replace(`/terminal/${selectedDeviceId.value}`)
  } else {
    router.replace('/terminal')
  }

  if (connected.value) {
    disconnect()
  }
  sessionId.value = null
  error.value = ''
}

// 窗口大小变化时重新 fit
const handleResize = () => {
  if (fitAddon.value) {
    fitAddon.value.fit()
  }
}

// Lifecycle
onMounted(async () => {
  initTerminal()

  // 连接 WebSocket 并获取设备列表
  initWebSocket()

  // 从路由参数获取设备 ID
  const deviceId = route.params.deviceId as string
  if (deviceId) {
    selectedDeviceId.value = deviceId
  }

  window.addEventListener('resize', handleResize)
})

// Watch devices list
watch(devices, (newDevices) => {
  console.log('[Terminal] Devices changed:', newDevices.length, newDevices)
  // 如果只有一个设备，自动选择
  if (newDevices.length === 1 && !selectedDeviceId.value) {
    selectedDeviceId.value = newDevices[0].device_id
    console.log('[Terminal] Auto-selected device:', selectedDeviceId.value)
  }
}, { immediate: true })

onBeforeUnmount(() => {
  if (connected.value) {
    disconnect()
  }

  if (wsClient && messageHandler) {
    wsClient.off('message', messageHandler)
  }

  terminal.value?.dispose()
  window.removeEventListener('resize', handleResize)
})

// 监听路由参数变化
watch(() => route.params.deviceId, (newDeviceId) => {
  if (newDeviceId && typeof newDeviceId === 'string') {
    selectedDeviceId.value = newDeviceId
    if (connected.value) {
      disconnect()
    }
  }
})
</script>

<template>
  <div class="terminal-page">
    <!-- 工具栏 -->
    <div class="terminal-toolbar">
      <div class="toolbar-left">
        <Select
          v-model="selectedDeviceId"
          :options="onlineDevices"
          optionLabel="name"
          optionValue="device_id"
          placeholder="选择设备"
          class="device-select"
          @change="onDeviceChange"
        >
          <template #option="slotProps">
            <div class="flex items-center gap-2">
              <span>{{ slotProps.option.name || slotProps.option.device_id.slice(0, 12) }}</span>
              <Tag v-if="slotProps.option.is_online" value="在线" severity="success" />
            </div>
          </template>
        </Select>

        <Button
          label="连接"
          icon="pi pi-link"
          severity="success"
          :disabled="!canConnect"
          @click="connect"
        />
        <Button
          label="断开"
          icon="pi pi-times"
          severity="danger"
          :disabled="!connected"
          @click="disconnect"
        />
        <Button
          label="清屏"
          icon="pi pi-trash"
          severity="secondary"
          :disabled="!terminal"
          @click="clearTerminal"
        />
      </div>

      <div class="toolbar-right">
        <Tag :value="statusText" :severity="statusSeverity" />
      </div>
    </div>

    <!-- 终端区域 -->
    <div class="terminal-wrapper" ref="terminalWrapper">
      <div ref="terminalElement" class="terminal"></div>
    </div>

    <!-- 错误提示 -->
    <div v-if="error" class="terminal-error">
      <i class="pi pi-exclamation-triangle mr-2"></i>
      {{ error }}
    </div>
  </div>
</template>

<style scoped>
.terminal-page {
  display: flex;
  flex-direction: column;
  height: calc(100vh - 60px);
  background: #1e1e2e;
}

.terminal-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 16px;
  background: #181825;
  border-bottom: 1px solid #313244;
}

.toolbar-left {
  display: flex;
  gap: 8px;
  align-items: center;
}

.device-select {
  width: 200px;
}

.terminal-wrapper {
  flex: 1;
  padding: 8px;
  overflow: hidden;
}

.terminal {
  height: 100%;
}

.terminal-error {
  position: fixed;
  bottom: 20px;
  right: 20px;
  padding: 12px 20px;
  background: #f38ba8;
  color: #1e1e2e;
  border-radius: 8px;
  font-size: 13px;
  display: flex;
  align-items: center;
}
</style>

<style>
/* xterm.js 全局样式 */
.terminal .xterm-viewport::-webkit-scrollbar {
  width: 8px;
}

.terminal .xterm-viewport::-webkit-scrollbar-track {
  background: #1e1e2e;
}

.terminal .xterm-viewport::-webkit-scrollbar-thumb {
  background: #45475a;
  border-radius: 4px;
}

.terminal .xterm-viewport::-webkit-scrollbar-thumb:hover {
  background: #585b70;
}
</style>
